package io.legado.app.constant

object EventBus {
    const val MEDIA_BUTTON = "mediaButton"
    const val RECREATE = "RECREATE"
    const val UP_BOOKSHELF = "upBookToc"
    const val BOOKSHELF_REFRESH = "bookshelfRefresh"
    const val ALOUD_STATE = "aloud_state"
    const val TTS_PROGRESS = "ttsStart"
    const val AUDIO_DS = "audioDs"
    const val READ_ALOUD_DS = "readAloudDs"
    const val BATTERY_CHANGED = "batteryChanged"
    const val TIME_CHANGED = "timeChanged"
    const val UP_CONFIG = "upConfig"
    const val VIDEO_SUB_TITLE = "VideoSubTitle"
    const val AUDIO_SUB_TITLE = "audioSubTitle"
    const val AUDIO_STATE = "audioState"
    const val AUDIO_PROGRESS = "audioProgress"
    const val AUDIO_BUFFER_PROGRESS = "audioBufferProgress"
    const val AUDIO_SIZE = "audioSize"
    const val AUDIO_SPEED = "audioSpeed"
    const val NOTIFY_MAIN = "notifyMain"
    const val WEB_SERVICE = "webService"
    const val UP_DOWNLOAD = "upDownload"
    const val UP_DOWNLOAD_STATE = "upDownloadState"
    const val SAVE_CONTENT = "saveContent"
    const val CHECK_SOURCE = "checkSource"
    const val CHECK_SOURCE_DONE = "checkSourceDone"
    const val TIP_COLOR = "tipColor"
    const val SOURCE_CHANGED = "sourceChanged"
    const val SEARCH_RESULT = "searchResult"
    const val UPDATE_READ_ACTION_BAR = "updateReadActionBar"
    const val UP_SEEK_BAR = "upSeekBar"
    const val READ_ALOUD_PLAY = "readAloudPlay"
    const val EXPORT_BOOK = "exportBook"
    const val UP_MANGA_CONFIG = "upMangaConfig"
    const val PLAY_MODE_CHANGED = "playModeChanged"
    const val REFRESH_BOOK_INFO = "refreshBookInfo"
    const val REFRESH_BOOK_CONTENT = "refreshBookContent"
    const val REFRESH_BOOK_TOC = "refreshBookToc"
    const val MATERIALS_CHANGED = "materialsChanged"
    const val BREAKDOWNS_CHANGED = "breakdownsChanged"
    const val BREAKDOWN_AI_PROGRESS = "breakdownAiProgress"
    /** AI Agent 会话消息流新增/流式增量/状态变更(convId:Long payload),对话页用来滚动刷新 */
    const val AI_AGENT_MSG_UPDATED = "aiAgentMsgUpdated"
    /** AI Agent 新建/删除/切换会话(convId:Long or -1 代表刷新侧栏列表) */
    const val AI_AGENT_CONV_CHANGED = "aiAgentConvChanged"
    /** Skill 变动(增删改)时通知 Skill 列表与拆书档案页绑定选择器刷新 */
    const val AI_AGENT_SKILL_CHANGED = "aiAgentSkillChanged"
    const val UP_VIDEO_INFO = "upVideoInfo"
}
